# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_userfeature_user_feature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarea',
            name='new_area_short',
            field=models.CharField(default='dummy', max_length=7),
            preserve_default=False,
        ),
    ]
