# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_newarea_new_area_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='new_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.NewArea'),
        ),
    ]
