# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_system_new_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeature',
            name='user_feature_documentation_reviewed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
