# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itservices', '0002_auto_20160308_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('name', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('itservice', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService')),
            ],
        ),
        migrations.CreateModel(
            name='Landspace',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='landspace',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace'),
        ),
    ]
