# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_vm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vm',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='container',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='technology',
        ),
    ]
