# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_containertechnology_vmtechnology'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='technology',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='systems.ContainerTechnology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vm',
            name='technology',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='systems.VMTechnology'),
            preserve_default=False,
        ),
    ]
