# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_auto_20160310_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClusterMapComputer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='systems.Cluster')),
                ('computer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='systems.Computer')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterRoles',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clustermapcomputer',
            name='role',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='systems.ClusterRoles'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='technology',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='systems.ClusterTechnology'),
        ),
    ]
