# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itservices', '0002_auto_20160308_2022'),
        ('systems', '0012_auto_20160310_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClusterMapComputer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='systems.Cluster')),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClusterTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComputerRole',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContainerTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostPlug',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HostTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('host', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='systems.HostPlug')),
                ('itservice', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService')),
                ('landspace', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace')),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VMTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vm',
            name='technology',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='systems.VMTechnology'),
        ),
        migrations.AddField(
            model_name='container',
            name='host',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='systems.HostPlug'),
        ),
        migrations.AddField(
            model_name='container',
            name='itservice',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService'),
        ),
        migrations.AddField(
            model_name='container',
            name='landspace',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace'),
        ),
        migrations.AddField(
            model_name='container',
            name='technology',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='systems.ContainerTechnology'),
        ),
        migrations.AddField(
            model_name='computer',
            name='host_plug',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='systems.HostPlug'),
        ),
        migrations.AddField(
            model_name='computer',
            name='itservice',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService'),
        ),
        migrations.AddField(
            model_name='computer',
            name='landspace',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace'),
        ),
        migrations.AddField(
            model_name='clustermapcomputer',
            name='computer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='systems.Computer'),
        ),
        migrations.AddField(
            model_name='clustermapcomputer',
            name='itservice',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService'),
        ),
        migrations.AddField(
            model_name='clustermapcomputer',
            name='landspace',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace'),
        ),
        migrations.AddField(
            model_name='clustermapcomputer',
            name='role',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='systems.ComputerRole'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='cluster_technology',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='systems.ClusterTechnology'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='host_plug',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='systems.HostPlug'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='itservice',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='landspace',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace'),
        ),
    ]
