# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_auto_20160312_0615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VMTechnology',
            new_name='VirtualizationTechnology',
        ),
        migrations.RemoveField(
            model_name='container',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='hostinstance',
            name='host_technology',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='technology',
        ),
        migrations.DeleteModel(
            name='ContainerTechnology',
        ),
        migrations.DeleteModel(
            name='HostTechnology',
        ),
    ]
