# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0015_auto_20160312_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='virtualization_technology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='systems.VirtualizationTechnology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostinstance',
            name='virtualization_technology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='systems.VirtualizationTechnology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vm',
            name='virtualization_technology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='systems.VirtualizationTechnology'),
            preserve_default=False,
        ),
    ]
