# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0016_auto_20160312_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostinstance',
            options={},
        ),
        migrations.RemoveField(
            model_name='hostinstance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hostinstance',
            name='itservice',
        ),
        migrations.RemoveField(
            model_name='hostinstance',
            name='landspace',
        ),
        migrations.RemoveField(
            model_name='hostinstance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hostinstance',
            name='note',
        ),
        migrations.AlterField(
            model_name='cluster',
            name='host_plug',
            field=models.OneToOneField(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to='systems.HostPlug'),
        ),
    ]
