# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0018_auto_20160312_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('vendor', models.CharField(max_length=75)),
                ('arch', models.CharField(max_length=75)),
                ('frequency', models.CharField(max_length=75)),
                ('cores', models.IntegerField()),
                ('computer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='systems.Computer')),
            ],
        ),
    ]
