# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(max_length=8)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ITService',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('short', models.CharField(max_length=8)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('distribution_note', models.TextField(blank=True)),
                ('distribution', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='itservices.Distribution')),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='itservices.Group')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
